language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# - "3.7-dev"
os:
  # should mostly work?
  - osx
  - linux
matrix:
  allow_failures:
    - os: osx
install:
  - pip install -r requirements.txt
  - pip install pylint green
script:
  - python setup.py build
  # 2.7 operates all tests
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then green congredi; fi
  # 3.* operates tests we think should be compatible
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then ./scripts.sh v3works && echo "partial compatibility holding"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then ./scripts.sh v3breaks || echo "still incompatible"; fi
  - python setup.py install
  - pylint congredi
  - pip install mkdocs || echo "mkdocs problems"
  - mkdocs build || echo "Docs fail..."
#sudo: required : ubuntu/fedora/alpine/windows/osx/docker
#services:
# - docker
#script:
# - docker build -t test . 1>/dev/null
