language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
matrix:
  include:
    - os: linux
      python: 3.5
    - os: osx
      language: generic
  allow_failures:
    - os: osx
    - python: 2.6
    - python: 3.2
    - python: 3.3
    - python: 3.4
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi
install:
  - pip install -r requirements.txt
  - pip install pylint green
script:
  - python setup.py build
  - green congredi
  - python setup.py install
  - pylint congredi
  - mkdocs build || echo "Docs fail..."
#sudo: required : ubuntu/fedora/alpine/windows/osx/docker
#services:
# - docker
#script:
# - docker build -t test . 1>/dev/null
