#sudo: required
language: python
# ubuntu/fedora/alpine tests?
#services:
# - docker
# todo... make python work on base travis instances...
# hopefully StringIO patch works...
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # PyPy versions
# cryptography isn't compatible with some versions of pypi?
#  - "pypy"
#  - "pypy"  # PyPy2 2.5.0
  - "pypy-5.3.1"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install setuptools-lint
# command to run tests
script:
# - docker build -t test . 1>/dev/null
  - python setup.py build
  - python setup.py test
  - python setup.py install
  - python setup.py lint || echo "Lint fails..."
  - mkdocs build || echo "Docs fail..."