# hopefully this works.
environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"
#    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -r requirements-windows.txt"
  - "%PYTHON%\\python.exe -m pip install green"

build: off

test_script:
  - IF "%PYTHON%" EQU "C:\Python27" %PYTHON%\\python.exe -m green -vvv
  - IF "%PYTHON%" NEQ "C:\Python27" %PYTHON%\\python.exe -m green -vvv congredi.auth congredi.extra congredi.storage congredi.term congredi.tests congredi.utils congredi.algos.test.test_router congredi.crypto.test.test_hash congredi.crypto.test.test_kdf congredi.crypto.test.test_threshold
