site_name: Congredi
docs_dir: docs
theme: journal
formats:
    - none
pages:
    - 'Home': 'README.md'
    - 'Contributing': 'docs/contributing.md'
    - 'Specification': 'docs/specification.md'
    - 'Extending':'docs/extending.md'
