site_name: Congredi
site_url: http://toxik.io/congredi
site_description: Peer To Peer Things
site_author: Github People
requirements_file: docs/requirements.txt
docs_dir: 'docs'
site_dir: '_site'
theme: flatly
pages:
    - 'index': 'index.md'
    - 'Contributing': 'contributing.md'
    - 'Specification':
         - 'About': 'specification.md'
         - 'commands': 'specification/commands.md'
         - 'data': 'specification/data.md'
         - 'packets': 'specification/packets.md'
    - 'Extending': 'extending.md'
repo_url: https://github.com/thetoxicarcade/congredi