site_name: Congredi
site_url: http://congredi.io
site_description: Peer To Peer Things
site_author: Github People
requirements_file: docs/requirements.txt
docs_dir: 'docs'
site_dir: '_site'
theme: flatly
use_directory_urls: true
pages:
    - 'index': 'index.md'
    - 'Setup': 'Setup.md'

repo_url: https://github.com/thetoxicarcade/congredi