site_name: Congredi
site_url: http://congredi.io
site_description: Peer To Peer Things
site_author: Github People
requirements_file: docs/requirements.txt
docs_dir: 'docs'
site_dir: '_site'
theme: flatly
use_directory_urls: true
pages:
    - 'index': 'index.md'
    - 'Contributing':
         - 'intro': 'contributing/intro.md'
         - 'style': 'contributing/style.md'
         - 'tests': 'contributing/tests.md'
         - 'commits': 'contributing/commits.md'
         - 'Tags/Emoji': 'contributing/tags.md'
    - 'Extending':
         - 'angular': 'extending/angular.md'
         - 'database': 'extending/database.md'
    # - 'Specification':
    #      - 'About': 'specification/about.md'
    #      - 'commands': 'specification/commands.md'
    #      - 'data': 'specification/data.md'
    #      - 'packets': 'specification/packets.md'
    # - 'data': 'data/chains.md'
    - 'commands':
        - 'Design': 'spec/commands/index.md'
        - 'current': 'spec/commands/idx/current.md'
        - 'future': 'spec/commands/idx/future.md'
        - 'past': 'spec/commands/idx/past.md'
        - 'search': 'spec/commands/idx/search.md'
        - 'publish': 'spec/commands/rw/publish.md'
        - 'deploy': 'spec/commands/rw/deploy.md'
        - 'subscribe': 'spec/commands/rw/subscribe.md'
        - 'monitor': 'spec/commands/rw/monitor.md'
repo_url: https://github.com/thetoxicarcade/congredi