site_name: Congredi
site_url: http://congredi.io
site_description: Peer To Peer Things
site_author: Github People
requirements_file: docs/requirements.txt
docs_dir: 'docs'
site_dir: '_site'
theme: flatly
use_directory_urls: true
pages:
    - 'index': 'index.md'
    - 'Contributing':
         - 'intro': 'contributing/intro.md'
         - 'style': 'contributing/style.md'
         - 'tests': 'contributing/tests.md'
         - 'commits': 'contributing/commits.md'
         - 'Tags/Emoji': 'contributing/tags.md'
    - 'Extending':
         - 'angular': 'extending/angular.md'
         - 'database': 'extending/database.md'
    - 'Specification':
         - 'Commands': 'spec/commands.md'
         - 'Storage': 'spec/storage.md'
         - 'Packets': 'spec/packet.md'

repo_url: https://github.com/thetoxicarcade/congredi